ada/tech-666: add dataLayer.push into amplitude's trackEvent method
rentspree/tracker pull request #24
Opened 2024-01-05 03:21 UTC by peeramit-rentspree

call dataLayer.push when an event is tracked via amplitude

2024-01-05 03:34 UTC, donus3 commented
@peeramit-rentspree Can we add the ability to disable the dataLayer push? For instance, add one flag to the amplitude tracker contractor options agrs and set the default value to `true`

2024-01-05 04:25 UTC, peeramit-rentspree commented
> @peeramit-rentspree Can we add the ability to disable the dataLayer push? For instance, add one flag to the amplitude tracker contractor options agrs and set the default value to `true`

fixed krub

2024-01-05 04:29 UTC, donus3 commented on src/tracker/amplitude.js
> +    this.pushToDataLayer = options.pushToDataLayer === false ? false : true
You can turn the boolean short hand condition into an instantly boolean transform by:

```suggestion
    this.pushToDataLayer = !!options.pushToDataLayer
```

2024-01-05 04:35 UTC, donus3 commented on src/tracker/amplitude.js
> +    this.pushToDataLayer = options.pushToDataLayer === false ? false : true
Resolved, the suggestion does not work if the option is undefined because we need to have a true value

2024-01-05 04:36 UTC, donus3 commented
LGTM!

2024-01-05 04:40 UTC, donus3 approved these changes
LGTM

2024-01-05 06:30 UTC, moyarnadhis approved these changes
LGTM

2024-01-08 03:46 UTC, donus3 requested changes

2024-01-08 03:46 UTC, donus3 commented on src/tracker/gtm.js
> +   * @returns {Function | Proxy} the amplitude instance if it exist,
```suggestion
   * @returns {Function | Proxy} the GTM data layer instance if it exists,
```

2024-01-08 03:46 UTC, donus3 commented on src/tracker/gtm.js
> +   * Identify the user by calling `gtag("config", ...userObject)`
```suggestion
   * Identify the user by setting the userId to the data layer instance so that when
   * calling trackEvent we can automatically attach the userId to each event.
```

2024-01-08 03:46 UTC, donus3 commented on src/tracker/gtm.js
> +  getUserIdFromDataLayer() {
please add the js doc for this method

2024-01-08 03:46 UTC, donus3 commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
Please use this.getTracker function to ensure the existence of the instance.
One more point, if the instance is null or undefined, when you call the set function it will throw an error "set is not a function of undefined".

2024-01-08 05:58 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
fixed krub

2024-01-08 06:30 UTC, donus3 commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
why do we need the get a specific gtm datalayer method? How difference between `getTracker()` and `getSpecificDataLayer()`

2024-01-08 06:34 UTC, donus3 commented on src/tracker/gtm.js
> +  getUserIdFromDataLayer() {
I would suggest
```js
/**
 *  returns the userId from the GTM data layer instance if the instance does exist.
 *  otherwise returns undefined
 *  @returns {string | undefined} the userId from the data layer
 */
```

2024-01-08 06:35 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
from what tried in the browser's console, the generic dataLayer (window.dataLayer) doesn't have the getter setter functions, only push, while the specific one (window['google_tag_manager'][this.trackingId].dataLayer) does, but doesn't have push krub

2024-01-08 07:01 UTC, donus3 commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
Got it. I think setting the value to the data layer variable does not introduce any benefit compared to setting the value to the class attribute (`this.userId`). 
So, let's set the value to the Tracker attribute instead and remove the methods that involve the `window['google_tag_manager'][this.trackingId]`

2024-01-08 07:51 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +   * @returns {Function | Proxy} the amplitude instance if it exist,
fixed

2024-01-08 07:59 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +   * Identify the user by calling `gtag("config", ...userObject)`
changed

2024-01-08 07:59 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +  getUserIdFromDataLayer() {
removed as discussed

2024-01-08 08:00 UTC, peeramit-rentspree commented on src/tracker/gtm.js
> +    window['google_tag_manager'][this.trackingId].dataLayer.set('userId', mappedProfile.userId)
fixed again krub

2024-01-08 08:21 UTC, donus3 commented on src/tracker/gtm.js
> + * @param {String} options.userId the user ID of the current user associated with this tracker instance, may be undefined
```suggestion
 * @param {String | undefined} options.userId the user ID of the current user associated with this tracker instance, may be undefined
```

2024-01-08 08:28 UTC, donus3 approved these changes
LGTM!

2024-01-08 08:30 UTC, moyarnadhis approved these changes
trying to add the approve counts

2024-01-08 08:54 UTC, puttpotsawee commented on src/tracker/gtm.js
> +  }
@peeramit-rentspree I guess this function is static because you want to access `window` as a global variable
this makes this tracker different from the others as the `getTracker` function is static (It does probably not override the `BaseTracker` abstract class. Moreover, you can notice that you need to call this static function in the `trackEvent` function and the mock test is also different.

Consider adding another static class instead, since we want to refer to `dataLayer` from the `window` global object, we can then create a static class that return the `window` object instead: `static getWindow`

Considering this implementation, we can then also add error message if `window` is undefined etc and not having to worry about that in this function to maintain single responsibility

2024-01-08 09:06 UTC, merged